name: status_alert
description: Display Apple system-like self-hiding status alerts. It is well suited for notifying user without interrupting user flow.
version: 1.0.1
homepage: https://github.com/yako-dev/flutter-status-alert

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #flare_flutter: ^3.0.2
  flare_flutter:
    git:
    #  url: https://github.com/tsinis/Flare-Flutter.git
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  fonts:
    - family: SFNS
      fonts:
        - asset: assets/fonts/SFNS.ttf
