name: bdaya_shared_value
description: A straightforward way to manage global state in flutter apps.
version: 3.1.3
homepage: https://github.com/Bdaya-Dev/flutter-shared-value

environment:
 sdk: ">=3.0.0 <4.0.0"
 flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
