name: notifi
description: "Crowtech Common Library."

version: 0.0.75
#homepage:

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: '>=3.27.0-2.0.pre.38697'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git

  android_id: ^0.4.0
  app_badge_plus: ^1.1.2
  app_set_id: ^1.2.1
  async: ^2.11.0
  badges: ^3.1.2
  background_fetch: ^1.3.7
  #bdaya_shared_value: ^3.1.3
  bdaya_shared_value: #^3.1.3
     path: ../flutter-shared-value
  cached_network_image: ^3.0.0
  camera: ^0.11.1
  device_info_plus: ^11.2.1
  dropdown_button2: ^2.3.9
  email_validator: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  flutter_map_animations: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  #easy_web_view: ^2.1.0
  flutter_form_builder: ^10.0.1
  flutter_osm_plugin: ^1.3.7
  flutter_hooks: ^0.20.5
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
   #  path: ../flutter_map_location_marker
  firebase_messaging: ^15.1.3
  
  flutter_local_notifications: ^18.0.1
  flutter_regex: ^0.0.3
  flutter_riverpod:
  #flutter_rotation_sensor: ^0.1.0
  fluttertoast: ^8.2.11
  flutter_secure_storage: any
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.8.0 
  force_update_helper: ^0.1.5
  form_builder_validators: ^11.1.2
  freezed_annotation: ^2.4.4
  #get_storage: ^2.1.1
  geolocator: ^14.0.0
  go_router: ^14.7.2
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  latlng: ^2.0.7 
  latlong2: ^0.9.1
  logger: ^2.5.0
  minio: ^3.5.7
  mockito: ^5.0.13
  #oidc: ^0.9.0+1
  oidc: 
    path: ../oidc/packages/oidc 
  oidc_core: #^0.9.1
    path: ../oidc/packages/oidc_core 
  oidc_default_store: #^0.2.0+12
    path: ../oidc/packages/oidc_default_store
  onboarding: ^4.0.2
  package_info_plus: ^8.1.1 
  pointer_interceptor: ^0.10.1+2
  posthog_flutter: ^4.7.1 
  provider: ^6.1.2
  riverpod_annotation: ^2.6.1
  riverpod_cache: ^0.0.2
  rxdart: any 
  session_storage: any
  shimmer: ^3.0.0
  slang: ^4.6.0
  slang_flutter: ^4.6.0
  smooth_page_indicator: ^1.2.1
  status_alert: 
     path: ../flutter-status-alert
  url_strategy: ^0.3.0
  uuid: ^4.5.1 
  
  video_player: ^2.9.2
  async_textformfield: ^3.0.1+1
  #html_editor_enhanced: ^2.6.0
  osm_flutter_hooks: ^1.4.1
 
  fleather: ^1.22.0

  


  
  
  
  

#  riverpod_infinite_scroll_pagination: ^1.0.3



#  rxdart: ^0.27.7
  #infinite_scroll_pagination: 5.0.0
  #infinite_scroll_pagination: 
 #  path:  ../infinite_scroll_pagination



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  custom_lint: any 
  json_serializable: ^6.9.0

  flutter_launcher_icons: ^0.14.3
 
  flutter_web_plugins:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.8
  go_router_builder: ^2.7.5
  riverpod_lint: any #^2.6.4
  riverpod_generator: any #^2.6.4
  slang_build_runner: ^4.6.0 # ONLY if you use build_runner (2/2)
  # Localization
  slang_gpt: ^0.11.0
  very_good_analysis: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  generate: true
  uses-material-design: true
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 200
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style : italic

assets:
    - assets/
    - assets/images/markers/
    - welcome.json
