name: notifi
description: "Notification Package."
version: 0.0.3
#homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  android_id: ^0.4.0
  app_set_id: ^1.2.1
  async: ^2.11.0
  bdaya_shared_value: ^3.1.3
  device_info_plus: ^10.1.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  fluttertoast: ^8.2.8
  flutter_secure_storage: any
  firebase_core: ^3.8.0
  get_storage: ^2.1.1
  go_router: ^14.6.0
  intl: any
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  oidc: ^0.9.0+1
  oidc_core: ^0.9.1
  oidc_default_store: ^0.2.0+12
  package_info_plus: ^8.1.1
  provider: ^6.1.2
  session_storage: any
  flutter_dotenv: ^5.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
