name: notifi
description: "Notification Package."
version: 0.0.23
#homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git

  android_id: ^0.4.0
  app_set_id: ^1.2.1
  async: ^2.11.0
  bdaya_shared_value: ^3.1.3
  device_info_plus: ^11.2.1
  dropdown_button2: ^2.3.9
  flutter_map: ^5.0.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  flutter_riverpod:
  fluttertoast: ^8.2.8
  flutter_secure_storage: any
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.8.0
  get_storage: ^2.1.1
  geolocator: ^13.0.2
  go_router: ^14.6.0
  intl: any
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  latlng: ^2.0.7
  latlong2: ^0.9.1
  logger: ^2.5.0
  mockito: ^5.0.13
  oidc: ^0.9.0+1
  oidc_core: ^0.9.1
  oidc_default_store: ^0.2.0+12
  onboarding: ^4.0.2
  package_info_plus: ^8.1.1
  posthog_flutter: ^4.7.1
  provider: ^6.1.2
  rxdart: any 
  session_storage: any
  slang: ^4.1.1
  slang_flutter: ^4.2.0
  uuid: any 
  #riverpod: ^2.6.1
  #hooks_riverpod: ^2.6.1
  #flutter_riverpod: ^2.6.1
  #riverpod_annotation: ^2.6.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  slang_build_runner: ^4.4.0 # ONLY if you use build_runner (2/2)
  # Localization
  slang_gpt: ^0.11.0

#    path: ../
  flutter_launcher_icons: ^0.14.2
  custom_lint: any 
  flutter_lints: ^1.0.0
  #riverpod_generator: ^2.6.1
  #custom_lint: any 
  #custom_lint: ^0.7.0 
  riverpod_lint: ^2.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

assets:
    - assets/
    - assets/images/markers/