// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'fcm.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$Fcm {
  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is Fcm);
  }

  @override
  int get hashCode => runtimeType.hashCode;

  @override
  String toString() {
    return 'Fcm()';
  }
}

/// @nodoc
class $FcmCopyWith<$Res> {
  $FcmCopyWith(Fcm _, $Res Function(Fcm) __);
}

/// @nodoc

class Active extends Fcm {
  const Active(
      {required this.firebaseOptions,
      required this.vapidKey,
      required this.secondsToast,
      required final List<String> topics,
      required this.token})
      : _topics = topics,
        super._();

  /// Platform-specific Firebase configuration options
  ///
  /// Contains the Firebase project configuration including:
  /// - API keys and project identifiers
  /// - Platform-specific settings (iOS, Android, Web)
  /// - Authentication and messaging configurations
  ///
  /// **Note:** May be null for platforms where Firebase is not available
  /// or when using alternative push notification services.
  final FirebaseOptions? firebaseOptions;

  /// VAPID key for web push notifications
  ///
  /// Voluntary Application Server Identification (VAPID) key used for
  /// web push notifications. This key identifies the application server
  /// to the push service and is required for web-based notifications.
  ///
  /// **Note:** Required for web platforms, may be null for mobile-only apps.
  final String? vapidKey;

  /// Duration in seconds for toast notification display
  ///
  /// Controls how long toast notifications remain visible to the user.
  /// This affects user experience and notification visibility.
  ///
  /// **Recommended values:**
  /// - 3-5 seconds for informational messages
  /// - 5-10 seconds for important alerts
  /// - Consider accessibility requirements for longer durations
  final int secondsToast;

  /// List of notification topics the user is subscribed to
  ///
  /// Topics allow for targeted messaging to specific user groups or
  /// interests. Users can subscribe to multiple topics to receive
  /// relevant notifications.
  ///
  /// **Examples:**
  /// - ['news', 'alerts', 'updates'] for general app notifications
  /// - ['sports', 'weather', 'breaking'] for news app categories
  /// - ['team-alpha', 'project-beta'] for organization-specific topics
  ///
  /// **Business Rules:**
  /// - Topic names should follow Firebase naming conventions
  /// - Users should be able to subscribe/unsubscribe from topics
  /// - Empty list indicates no topic subscriptions
  final List<String> _topics;

  /// List of notification topics the user is subscribed to
  ///
  /// Topics allow for targeted messaging to specific user groups or
  /// interests. Users can subscribe to multiple topics to receive
  /// relevant notifications.
  ///
  /// **Examples:**
  /// - ['news', 'alerts', 'updates'] for general app notifications
  /// - ['sports', 'weather', 'breaking'] for news app categories
  /// - ['team-alpha', 'project-beta'] for organization-specific topics
  ///
  /// **Business Rules:**
  /// - Topic names should follow Firebase naming conventions
  /// - Users should be able to subscribe/unsubscribe from topics
  /// - Empty list indicates no topic subscriptions
  List<String> get topics {
    if (_topics is EqualUnmodifiableListView) return _topics;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(_topics);
  }

  /// Device-specific FCM registration token
  ///
  /// Unique identifier for this device/app instance, used for sending
  /// targeted push notifications. This token is generated by Firebase
  /// and may change periodically.
  ///
  /// **Important:**
  /// - Token should be refreshed when it changes
  /// - Token is required for device-specific notifications
  /// - Token should be sent to your notification service backend
  final String token;

  /// Create a copy of Fcm
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $ActiveCopyWith<Active> get copyWith =>
      _$ActiveCopyWithImpl<Active>(this, _$identity);

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Active &&
            (identical(other.firebaseOptions, firebaseOptions) ||
                other.firebaseOptions == firebaseOptions) &&
            (identical(other.vapidKey, vapidKey) ||
                other.vapidKey == vapidKey) &&
            (identical(other.secondsToast, secondsToast) ||
                other.secondsToast == secondsToast) &&
            const DeepCollectionEquality().equals(other._topics, _topics) &&
            (identical(other.token, token) || other.token == token));
  }

  @override
  int get hashCode => Object.hash(runtimeType, firebaseOptions, vapidKey,
      secondsToast, const DeepCollectionEquality().hash(_topics), token);

  @override
  String toString() {
    return 'Fcm.active(firebaseOptions: $firebaseOptions, vapidKey: $vapidKey, secondsToast: $secondsToast, topics: $topics, token: $token)';
  }
}

/// @nodoc
abstract mixin class $ActiveCopyWith<$Res> implements $FcmCopyWith<$Res> {
  factory $ActiveCopyWith(Active value, $Res Function(Active) _then) =
      _$ActiveCopyWithImpl;
  @useResult
  $Res call(
      {FirebaseOptions? firebaseOptions,
      String? vapidKey,
      int secondsToast,
      List<String> topics,
      String token});
}

/// @nodoc
class _$ActiveCopyWithImpl<$Res> implements $ActiveCopyWith<$Res> {
  _$ActiveCopyWithImpl(this._self, this._then);

  final Active _self;
  final $Res Function(Active) _then;

  /// Create a copy of Fcm
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  $Res call({
    Object? firebaseOptions = freezed,
    Object? vapidKey = freezed,
    Object? secondsToast = null,
    Object? topics = null,
    Object? token = null,
  }) {
    return _then(Active(
      firebaseOptions: freezed == firebaseOptions
          ? _self.firebaseOptions
          : firebaseOptions // ignore: cast_nullable_to_non_nullable
              as FirebaseOptions?,
      vapidKey: freezed == vapidKey
          ? _self.vapidKey
          : vapidKey // ignore: cast_nullable_to_non_nullable
              as String?,
      secondsToast: null == secondsToast
          ? _self.secondsToast
          : secondsToast // ignore: cast_nullable_to_non_nullable
              as int,
      topics: null == topics
          ? _self._topics
          : topics // ignore: cast_nullable_to_non_nullable
              as List<String>,
      token: null == token
          ? _self.token
          : token // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc

class Inactive extends Fcm {
  const Inactive() : super._();

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is Inactive);
  }

  @override
  int get hashCode => runtimeType.hashCode;

  @override
  String toString() {
    return 'Fcm.inactive()';
  }
}

// dart format on
