name: Example
description: Crowtech Notifi Example 
publish_to: none
version: 0.0.1+1

environment:
 sdk: ">=3.0.0 <4.0.0"
 flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #   path: ..
  notifi:
    path:  ../

  # notifi:
  #   git:
  #     url: https://github.com/Crowtech/notifi.git

  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git

    #vcontrol-start
  android_id: ^0.4.0
  app_set_id: ^1.2.1
  adaptive_action_sheet: ^2.0.3
  audioplayers: ^6.0.0
  async: ^2.11.0
  bdaya_shared_value: ^3.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter_app_badger: ^1.5.0
  flutter_inappwebview_web: ^1.1.2
  flutter_map: ^5.0.0
  flutter_onboarding_slider: ^1.0.11
  flutter_secure_storage: 9.2.2
  flutter_speed_dial: ^7.0.0
  go_router: ^14.6.0
  http: ^1.2.2
  intl: any
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  #logging: ^1.2.0
  oidc: ^0.9.0+1
  oidc_core: ^0.9.1
  oidc_default_store: ^0.2.0+12
  onboarding: ^4.0.2
  package_info_plus: ^8.1.1
  path_provider: ^2.1.1
  posthog_flutter: ^4.7.1
  proj4dart: any
  provider: ^6.1.2
  session_storage: any
  shared_preferences: ^2.2.2
  slang: ^4.1.1
  slang_flutter: ^4.2.0
  jaguar_jwt: ^3.0.0
  universal_html: ^2.2.4
  workmanager: ^0.5.2

  freezed_annotation: ^2.4.4
  flutter_osm_plugin: ^1.3.6
  flutter_hooks: ^0.20.5
  pointer_interceptor: ^0.10.1+2
  firebase_core: ^3.9.0
  background_fetch: ^1.3.7
 #vcontrol-end


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2
  very_good_analysis: ^6.0.0

  flutter_driver:
    sdk: flutter
  #flutter_background_geolocation: ^4.16.2
  
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  slang_build_runner: 4.2.0 # ONLY if you use build_runner (2/2)
  # Localization
  slang_gpt: ^0.11.0

  flutter_launcher_icons: ^0.11.0
  freezed: ^2.5.7

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/app_launcher_icon.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 200
  assets:
    - assets/
    - assets/avatar_1.png
    - assets/avatar_2.png
    - assets/avatar_3.png
    - assets/avatar_4.png
    - assets/avatar_5.png
    - assets/avatar_6.png
    - assets/avatar_7.png
    - assets/thumbnail_1.png
    - assets/images/background_splash.png
    - assets/images/splash_logo.png
    - assets/animation/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/markers/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    #- assets/ProductIcon.png
